HW 13
Otus-DevOps-2017-11/IsaIdasheV_microservices pull request #1
Opened 2018-02-10 13:30 UTC by isaidashev

Выполнил основное и дополнительное задание

2018-02-13 11:37 UTC, aladmit approved these changes
В docker-1.log должен быть вывод команды docker images, чтобы я мог понять что свой образ был сделан. 

Задание со * у нас плохо сформулировано, подразумевалось что вы посмотрите вывод информации о контейнере, вывод информации об образе и скажете в чем же состоит отличие этих двух сущностей. Заменил формулировку на такую: "на основе вывода команд объясните чем отличается контейнер от образа".(напоминаю, что задание со * делать не обязательно)

2018-02-13 11:38 UTC, aladmit requested changes
Добавить вывод docker images.

2018-02-14 06:34 UTC, isaidashev commented
Добавил вывод в docker images. Пришлось пересоздать образы.

2018-02-14 12:04 UTC, aladmit approved these changes
Да, вот так хорошо, молодец 👍

2018-02-14 16:24 UTC, merged